"""chatmessages

Revision ID: 002
Revises: 001
Create Date: 2023-11-21 23:59:40.124764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessage',
    sa.Column('uniq_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('uniq_id'),
    sa.UniqueConstraint('uniq_id')
    )
    op.drop_table('playerscore')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerscore',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='playerscore_pkey')
    )
    op.drop_table('chatmessage')
    # ### end Alembic commands ###
