"""add audio

Revision ID: 003
Revises: 002
Create Date: 2023-11-22 10:22:46.450049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('is_text', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'chatmessage', ['uniq_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatmessage', type_='unique')
    op.drop_column('chatmessage', 'is_text')
    # ### end Alembic commands ###
