"""Add prompt column

Revision ID: 008
Revises: 007
Create Date: 2024-04-11 09:40:55.590321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imageprompt', sa.Column('text_prompt', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'imageprompt', ['uniq_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imageprompt', type_='unique')
    op.drop_column('imageprompt', 'text_prompt')
    # ### end Alembic commands ###
