"""imageurltable

Revision ID: 011
Revises: 010
Create Date: 2024-05-16 11:53:14.896563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011'
down_revision = '010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagerecognition',
    sa.Column('uniq_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatmessage_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chatmessage_id'], ['chatmessage.uniq_id'], ),
    sa.PrimaryKeyConstraint('uniq_id'),
    sa.UniqueConstraint('uniq_id')
    )
    op.create_unique_constraint(None, 'chatmessage', ['uniq_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatmessage', type_='unique')
    op.drop_table('imagerecognition')
    # ### end Alembic commands ###
