"""Add urls column in caht message

Revision ID: 012
Revises: 011
Create Date: 2024-05-16 12:41:05.877556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012'
down_revision = '011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagerecognition')
    op.add_column('chatmessage', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.drop_column('chatmessage', 'is_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('is_text', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('chatmessage', 'image_urls')
    op.create_table('imagerecognition',
    sa.Column('uniq_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatmessage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatmessage_id'], ['chatmessage.uniq_id'], name='imagerecognition_chatmessage_id_fkey'),
    sa.PrimaryKeyConstraint('uniq_id', name='imagerecognition_pkey')
    )
    # ### end Alembic commands ###
